function com_google_gwt_uibinder_test_UiBinderTestApp(){var O='bootstrap',P='begin',Q='gwt.codesvr.fr.onevu.gwt.uibinder.test.UiBinderTestApp=',R='gwt.codesvr=',S='fr.onevu.gwt.uibinder.test.UiBinderTestApp',T='startup',U='DUMMY',V=0,W='iframe',X='javascript:""',Y='position:absolute; width:0; height:0; border:none; left: -1000px;',Z=' top: -1000px;',$='CSS1Compat',_='<!doctype html>',ab='',bb='<html><head><\/head><body><\/body><\/html>',cb='undefined',db=/loaded|complete/,eb='DOMContentLoaded',fb=50,gb='Chrome',hb='eval("',ib=1,jb='");',kb='script',lb='javascript',mb='moduleStartup',nb='moduleRequested',ob='head',pb='meta',qb='name',rb='fr.onevu.gwt.uibinder.test.UiBinderTestApp::',sb='::',tb='gwt:property',ub='content',vb='=',wb='gwt:onPropertyErrorFn',xb='Bad handler "',yb='" for "gwt:onPropertyErrorFn"',zb='gwt:onLoadErrorFn',Ab='" for "gwt:onLoadErrorFn"',Bb='#',Cb='?',Db='/',Eb=/^\w+:\/\//,Fb='img',Gb='clear.cache.gif',Hb='baseUrl',Ib='fr.onevu.gwt.uibinder.test.UiBinderTestApp.nocache.js',Jb='base',Kb='//',Lb=/^\//,Mb=/^[a-zA-Z]+:\/\//,Nb='user.agent',Ob='webkit',Pb='safari',Qb='msie',Rb=10,Sb='ie10',Tb=9,Ub='ie9',Vb=8,Wb='ie8',Xb='gecko',Yb='gecko1_8',Zb='unknown',$b=2,_b=3,ac=4,bc='selectingPermutation',cc='fr.onevu.gwt.uibinder.test.UiBinderTestApp.devmode.js',dc="GWT module 'fr.onevu.gwt.uibinder.test.UiBinderTestApp' may need to be (re)compiled",ec=':',fc='.cache.js',gc='loadExternalRefs',hc='end',ic='http:',jc='file:',kc='_gwt_dummy_',lc='__gwtDevModeHook:fr.onevu.gwt.uibinder.test.UiBinderTestApp',mc=/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?\/.*$/,nc='Ignoring non-whitelisted Dev Mode URL: ',oc=':moduleBase';var o=window;var p=document;r(O,P);function q(){var a=o.location.search;return a.indexOf(Q)!=-1||a.indexOf(R)!=-1}
function r(a,b){if(o.__gwtStatsEvent){o.__gwtStatsEvent({moduleName:S,sessionId:o.__gwtStatsSessionId,subSystem:T,evtGroup:a,millis:(new Date).getTime(),type:b})}}
com_google_gwt_uibinder_test_UiBinderTestApp.__sendStats=r;com_google_gwt_uibinder_test_UiBinderTestApp.__moduleName=S;com_google_gwt_uibinder_test_UiBinderTestApp.__errFn=null;com_google_gwt_uibinder_test_UiBinderTestApp.__moduleBase=U;com_google_gwt_uibinder_test_UiBinderTestApp.__softPermutationId=V;com_google_gwt_uibinder_test_UiBinderTestApp.__computePropValue=null;com_google_gwt_uibinder_test_UiBinderTestApp.__getPropMap=null;com_google_gwt_uibinder_test_UiBinderTestApp.__installRunAsyncCode=function(){};com_google_gwt_uibinder_test_UiBinderTestApp.__gwtStartLoadingFragment=function(){return null};com_google_gwt_uibinder_test_UiBinderTestApp.__gwt_isKnownPropertyValue=function(){return false};com_google_gwt_uibinder_test_UiBinderTestApp.__gwt_getMetaProperty=function(){return null};var s=null;var t=o.__gwt_activeModules=o.__gwt_activeModules||{};t[S]={moduleName:S};var u;function v(){w();return u}
function w(){if(u){return}var a=p.createElement(W);a.src=X;a.id=S;a.style.cssText=Y+Z;a.tabIndex=-1;p.body.appendChild(a);u=a.contentDocument;if(!u){u=a.contentWindow.document}u.open();var b=document.compatMode==$?_:ab;u.write(b+bb);u.close()}
function A(k){function l(a){function b(){if(typeof p.readyState==cb){return typeof p.body!=cb&&p.body!=null}return db.test(p.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(p.removeEventListener){p.removeEventListener(eb,d,false)}if(e){clearInterval(e)}}}
if(p.addEventListener){p.addEventListener(eb,d,false)}var e=setInterval(function(){if(b()){d()}},fb)}
function m(c){function d(a,b){a.removeChild(b)}
var e=v();var f=e.body;var g;if(navigator.userAgent.indexOf(gb)>-1&&window.JSON){var h=e.createDocumentFragment();h.appendChild(e.createTextNode(hb));for(var i=V;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(e.createTextNode(j.substring(ib,j.length-ib)))}h.appendChild(e.createTextNode(jb));g=e.createElement(kb);g.language=lb;g.appendChild(h);f.appendChild(g);d(f,g)}else{for(var i=V;i<c.length;i++){g=e.createElement(kb);g.language=lb;g.text=c[i];f.appendChild(g);d(f,g)}}}
com_google_gwt_uibinder_test_UiBinderTestApp.onScriptDownloaded=function(a){l(function(){m(a)})};r(mb,nb);var n=p.createElement(kb);n.src=k;p.getElementsByTagName(ob)[V].appendChild(n)}
com_google_gwt_uibinder_test_UiBinderTestApp.__startLoadingFragment=function(a){return D(a)};com_google_gwt_uibinder_test_UiBinderTestApp.__installRunAsyncCode=function(a){var b=v();var c=b.body;var d=b.createElement(kb);d.language=lb;d.text=a;c.appendChild(d);c.removeChild(d)};function B(){var c={};var d;var e;var f=p.getElementsByTagName(pb);for(var g=V,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(qb),k;if(j){j=j.replace(rb,ab);if(j.indexOf(sb)>=V){continue}if(j==tb){k=i.getAttribute(ub);if(k){var l,m=k.indexOf(vb);if(m>=V){j=k.substring(V,m);l=k.substring(m+ib)}else{j=k;l=ab}c[j]=l}}else if(j==wb){k=i.getAttribute(ub);if(k){try{d=eval(k)}catch(a){alert(xb+k+yb)}}}else if(j==zb){k=i.getAttribute(ub);if(k){try{e=eval(k)}catch(a){alert(xb+k+Ab)}}}}}__gwt_getMetaProperty=function(a){var b=c[a];return b==null?null:b};s=d;com_google_gwt_uibinder_test_UiBinderTestApp.__errFn=e}
function C(){function e(a){var b=a.lastIndexOf(Bb);if(b==-1){b=a.length}var c=a.indexOf(Cb);if(c==-1){c=a.length}var d=a.lastIndexOf(Db,Math.min(c,b));return d>=V?a.substring(V,d+ib):ab}
function f(a){if(a.match(Eb)){}else{var b=p.createElement(Fb);b.src=a+Gb;a=e(b.src)}return a}
function g(){var a=__gwt_getMetaProperty(Hb);if(a!=null){return a}return ab}
function h(){var a=p.getElementsByTagName(kb);for(var b=V;b<a.length;++b){if(a[b].src.indexOf(Ib)!=-1){return e(a[b].src)}}return ab}
function i(){var a=p.getElementsByTagName(Jb);if(a.length>V){return a[a.length-ib].href}return ab}
function j(){var a=p.location;return a.href==a.protocol+Kb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==ab){k=h()}if(k==ab){k=i()}if(k==ab&&j()){k=e(p.location.href)}k=f(k);return k}
function D(a){if(a.match(Lb)){return a}if(a.match(Mb)){return a}return com_google_gwt_uibinder_test_UiBinderTestApp.__moduleBase+a}
function F(){var f=[];var g=V;var h=[];var i=[];function j(a){var b=i[a](),c=h[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(s){s(a,d,b)}throw null}
i[Nb]=function(){var a=navigator.userAgent.toLowerCase();if(function(){return a.indexOf(Ob)!=-1}())return Pb;if(function(){return a.indexOf(Qb)!=-1&&p.documentMode==Rb}())return Sb;if(function(){return a.indexOf(Qb)!=-1&&p.documentMode>=Tb}())return Ub;if(function(){return a.indexOf(Qb)!=-1&&p.documentMode>=Vb}())return Wb;if(function(){return a.indexOf(Xb)!=-1}())return Yb;return Zb};h[Nb]={gecko1_8:V,ie10:ib,ie8:$b,ie9:_b,safari:ac};__gwt_isKnownPropertyValue=function(a,b){return b in h[a]};com_google_gwt_uibinder_test_UiBinderTestApp.__getPropMap=function(){var a={};for(var b in h){if(h.hasOwnProperty(b)){a[b]=j(b)}}return a};com_google_gwt_uibinder_test_UiBinderTestApp.__computePropValue=j;o.__gwt_activeModules[S].bindings=com_google_gwt_uibinder_test_UiBinderTestApp.__getPropMap;r(O,bc);if(q()){return D(cc)}var k;try{alert(dc);return;var l=k.indexOf(ec);if(l!=-1){g=parseInt(k.substring(l+ib),Rb);k=k.substring(V,l)}}catch(a){}com_google_gwt_uibinder_test_UiBinderTestApp.__softPermutationId=g;return D(k+fc)}
function G(){if(!o.__gwt_stylesLoaded){o.__gwt_stylesLoaded={}}r(gc,P);r(gc,hc)}
B();com_google_gwt_uibinder_test_UiBinderTestApp.__moduleBase=C();t[S].moduleBase=com_google_gwt_uibinder_test_UiBinderTestApp.__moduleBase;var H=F();if(o){var I=!!(o.location.protocol==ic||o.location.protocol==jc);o.__gwt_activeModules[S].canRedirect=I;function J(){var b=kc;try{o.sessionStorage.setItem(b,b);o.sessionStorage.removeItem(b);return true}catch(a){return false}}
if(I&&J()){var K=lc;var L=o.sessionStorage[K];if(!mc.test(L)){if(L&&(window.console&&console.log)){console.log(nc+L)}L=ab}if(L&&!o[K]){o[K]=true;o[K+oc]=C();var M=p.createElement(kb);M.src=L;var N=p.getElementsByTagName(ob)[V];N.insertBefore(M,N.firstElementChild||N.children[V]);return false}}}G();r(O,hc);A(H);return true}
com_google_gwt_uibinder_test_UiBinderTestApp.succeeded=com_google_gwt_uibinder_test_UiBinderTestApp();